name: create-terraform-document

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push to PR branch
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: modules/*
          git-push: true